name = "EvilSortingAlgorithms"
uuid = "f063c450-0f86-4191-ac5d-c4b075945ce2"
authors = ["Lilith Orion Hafner <lilithhafner@gmail.com> and contributors"]
version = "0.0.0"

[deps]
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"

[compat]
Chairmarks = "1.3.1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
